/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'tertiary-container': '#40000d',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdadb',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#f23d5c',
        'secondary-fixed': '#6ffbbe',
        'on-primary-fixed-variant': '#3f465c',
        'on-surface': '#0b1c30',
        'surface-container': '#e5eeff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#92002a',
        'on-primary-fixed': '#131b2e',
        'surface-container-highest': '#d3e4fe',
        'inverse-surface': '#213145',
        'on-secondary': '#ffffff',
        'primary': '#000000',
        'surface-bright': '#f8f9ff',
        'error': '#ba1a1a',
        'primary-container': '#131b2e',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-container': '#7c839b',
        'outline-variant': '#c6c6cd',
        'tertiary': '#000000',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-tertiary-fixed': '#40000d',
        'outline': '#76777d',
        'surface-dim': '#cbdbf5',
        'on-surface-variant': '#45464d',
        'inverse-primary': '#bec6e0',
        'inverse-on-surface': '#eaf1ff',
        'primary-fixed': '#dae2fd',
        'on-background': '#0b1c30',
        'surface': '#f8f9ff',
        'on-secondary-fixed-variant': '#005236',
        'secondary-container': '#6cf8bb',
        'on-secondary-fixed': '#002113',
        'surface-container-high': '#dce9ff',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#565e74',
        'surface-container-low': '#eff4ff',
        'background': '#f8f9ff',
        'secondary': '#006c49',
        'on-error': '#ffffff',
        'on-secondary-container': '#00714d',
        'primary-fixed-dim': '#bec6e0',
        'surface-variant': '#d3e4fe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'container-margin': '24px',
        gutter: '16px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(-4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.2s ease-out',
      },
    },
  },
  plugins: [],
}