import i18n from './config'

const articleText = {
  startTitle: 'Set up your space', startSummary: 'Start with your profile and budget so totals reflect your reality.', start1: 'Open Profile to check your name, email, location, and language.', start2: 'In Dashboard, review the salary and budget section.', start3: 'Create categories from Dashboard > Categories to classify each expense.', startTip: 'Consistent categories make charts and reports more useful.',
  expensesTitle: 'Record and review expenses', expensesSummary: 'Use Expenses Feed as your daily entry point to stay in control.', expenses1: 'Go to Expenses Feed and press Add Transaction.', expenses2: 'Complete the name, amount, category, date, and comment.', expenses3: 'Filter by category, status, or date range to find transactions.', expenses4: 'Open a row to see details and change its payment status.', expensesTip: 'Record the expense the same day and add a short note.',
  fixedTitle: 'Organize your fixed expenses', fixedSummary: 'Separate recurring commitments from one-off expenses.', fixed1: 'Open Fixed Expenses and press New > New Template + Expense.', fixed2: 'Use New > Add Fixed Expense when a group already exists.', fixed3: 'Enter the amount, category, and due day.', fixed4: 'In Cards or Table view you can edit, pay, or delete an expense.', fixed5: 'Enable Calendar on desktop to review due dates and trends.', fixedTip: 'Use groups such as Housing, Subscriptions, or Services.',
  dashboardTitle: 'Read your Dashboard', dashboardSummary: 'Get a quick read of your situation before going into detail.', dashboard1: 'Review total expenses, main category, and monthly savings.', dashboard2: 'Open a recent expense to see its status and comments.', dashboard3: 'Switch between Summary, Templates, Categories, and Statistics.', dashboard4: 'Use Top Expenses by Spending to find where money is concentrated.',
  statsTitle: 'Explore statistics', statsSummary: 'Compare expenses by day, week, month, or year.', stats1: 'Open Dashboard > Statistics and select a period.', stats2: 'Choose the month, year, and day when needed.', stats3: 'Review the category distribution and expense trend.', stats4: 'Review the calendar or scroll through the 24 daily hours.',
  reportsTitle: 'Generate reports', reportsSummary: 'Use Reports for a detailed review of a period.', reports1: 'Open Reports from the side navigation.', reports2: 'Select the month and year to analyze.', reports3: 'Review the summary, categories, and transactions.', reports4: 'Use the report export action to keep or share information.',
  accountTitle: 'Manage your account', accountSummary: 'Keep your details up to date and protect access.', account1: 'In Profile edit your personal information or password.', account2: 'In Settings configure currency, time zone, and date format.', account3: 'Use Export Data in Profile to download a copy.', account4: 'Sign out from the profile menu on shared devices.',
}

const en = {
  supportEmailPlaceholder: 'you@example.com',
  languageNames: { en: 'English', es: 'Spanish', fr: 'French', it: 'Italian', nl: 'Dutch' },
  currencyNames: { EUR: 'Euro (€)', USD: 'US dollar ($)', GBP: 'Pound (£)', JPY: 'Yen (¥)' },
  timezoneNames: { madrid: 'Madrid (GMT+01:00)', newYork: 'New York (GMT-05:00)', london: 'London (GMT+00:00)' },
  settingsExtra: { profiles: 'Profiles', workspaces: 'Workspaces', loadingProfiles: 'Loading profiles...', active: 'active', noProfiles: 'You do not have any profiles configured yet.', newProfilePlaceholder: 'Name of the new profile', individual: 'Individual', family: 'Family', business: 'Business', add: 'Add', profileInfoHelp: 'Personal information and contact details are edited from the Profile view.', generalPreferences: 'General preferences', notifications: 'Notifications', notificationPrompt: 'Choose what you want to receive', push: 'Push', yourData: 'Your data', exportInformation: 'Export information', exportDescription: 'Download your expenses, fixed expenses, categories, and current preferences.', preparingExport: 'Preparing export...', accountManagement: 'Account management', deactivation: 'Deactivation', deactivationUnavailable: 'Permanent deactivation requires a confirmation flow on the server and is not yet available.', unavailable: 'Unavailable', updatePassword: 'Update password', updating: 'Updating...', deleteProfile: 'Delete profile', deleteProfileAria: 'Delete {{name}}', currentPasswordPlaceholder: 'Current password', newPasswordPlaceholder: 'New password (minimum 8)', confirmPasswordPlaceholder: 'Confirm new password' },
  navigation: { profile: 'Profile', signOut: 'Sign out', closeMenu: 'Close menu', notifications: 'View payment reminders', closeNotifications: 'Close reminders', enableNotifications: 'Enable notifications', notificationsBlocked: 'Notifications are blocked in the browser.' },
  notifications: { title: 'Payment reminder', dueToday: 'Due today', noneToday: 'You have no pending fixed payments today.' },
  loginPage: { headline: 'Master your capital with', headlineAccent: 'precision-grade', headlineSuffix: 'analytics.', description: 'Experience the next generation of financial management. Centralized controls, real-time insights, and institutional-grade security for your assets.', monthlyGrowth: 'MONTHLY GROWTH', activeAccounts: 'ACTIVE ACCOUNTS', dashboardAlt: 'Financial data dashboard', joinProfessionals: 'Join 10k+ professionals managing their wealth.', termsPrefix: 'By registering, you agree to our', termsOfService: 'Terms of Service', and: 'and', privacyPolicy: 'Privacy Policy', continueWith: 'OR CONTINUE WITH', mobileApp: 'MOBILE APP COMING SOON', loginError: 'Error signing in', registerError: 'Error registering' },
  profile: { title: 'User Profile', subtitle: 'Manage your personal information and account settings.', verified: 'Verified', edit: 'Edit Profile', changePassword: 'Change Password', personalInformation: 'PERSONAL INFORMATION', email: 'Email', phone: 'Phone', location: 'Location', language: 'Language', exportData: 'EXPORT DATA', exportDescription: 'Download a copy of all your financial activity and settings in standard formats.', json: 'JSON Format', csv: 'CSV Table', lastExport: 'Last export on {{date}}.', activityHistory: 'ACTIVITY HISTORY', viewAll: 'View all', action: 'Action', device: 'Device', dateTime: 'Date and time', login: 'Sign in', dataExport: 'Data export', passwordChange: 'Password change', activityBrowser: 'Chrome / macOS', activityMadrid: 'Madrid, ES (192.168.1.1)', activityDevice: 'FinTrack App / iPhone 14', activityBarcelona: 'Barcelona, ES (84.12.34.56)', deleteProfile: 'Delete profile', deleteProfileAria: 'Delete {{name}}' },
  user: { security: 'SECURITY & ACCESS', personalInformation: 'PERSONAL INFORMATION', fullName: 'Full Name', emailAddress: 'Email Address', phoneNumber: 'Phone Number', street: 'Street', houseNumber: 'House Number', city: 'City', country: 'Country', interfaceLanguage: 'Interface Language', cancel: 'Cancel', saveChanges: 'Save Changes', changePassword: 'CHANGE PASSWORD', currentPassword: 'Current Password', newPassword: 'New Password', confirmNewPassword: 'Confirm New Password', currentPasswordPlaceholder: 'Enter current password', newPasswordPlaceholder: 'Enter new password', confirmPasswordPlaceholder: 'Confirm new password', allFieldsRequired: 'All fields are required', passwordsMismatch: 'New passwords do not match', passwordLength: 'Password must be at least 6 characters', passwordUpdated: 'Password updated successfully', passwordUpdateFailed: 'Failed to update password' },
  support: { categoryAll: 'All', categories: { gettingStarted: 'Getting started', expenses: 'Expenses', fixedExpenses: 'Fixed expenses', analysis: 'Analysis', account: 'Account' }, center: 'Help center', title: 'Learn to control your expenses', intro: 'A practical guide to recording transactions, organizing fixed expenses, and turning data into decisions.', searchPlaceholder: 'Search a guide, for example: partial payment', searchLabel: 'Search the guide', clearSearch: 'Clear search', explore: 'Explore by topic', completeGuide: 'Complete guide', essentials: 'Everything essential, in one place', guideCount_one: '{{count}} guide', guideCount_other: '{{count}} guides', noGuide: 'We could not find that guide', tryAnother: 'Try another word or select “All”.', startQuestion: 'Not sure where to start?', startAnswer: 'Follow the guides in order: configure your account, record expenses, then review statistics.', tip: 'Tip:', faqTitle: 'Frequently asked questions', needHelp: 'Need more help?', request: 'Submit a request', requestDescription: 'Describe the problem with as much context as possible.', saved: 'Request saved successfully on this device.', name: 'Name', namePlaceholder: 'Your name', email: 'Email', subject: 'Subject', message: 'Message', messagePlaceholder: 'What were you trying to do and what happened?', saveRequest: 'Save request', completeFields: 'Complete your name, email, and message to submit the request.', subjects: { app: 'Question about the application', expense: 'Problem with an expense', fixed: 'Problem with a fixed expense', report: 'Problem with a report', suggestion: 'Suggestion' }, articles: articleText, faq: { differenceQ: 'What is the difference between an expense and a fixed expense?', differenceA: 'An expense is a one-off transaction. A fixed expense is a recurring commitment managed separately.', partialQ: 'What does a partial payment mean?', partialA: 'You have recorded only part of the original amount; the remaining balance is still shown.', missingQ: 'Why does an expense not appear in a statistic?', missingA: 'Check the selected period, active filters, and expense status.', editQ: 'Can I edit or delete a fixed expense?', editA: 'Yes. Open Cards or Table view and use Edit or Delete.', categoriesQ: 'How do I keep categories useful?', categoriesA: 'Use specific names and avoid duplicate categories.' } },
}

const es = { navigation: { profile: 'Perfil', signOut: 'Cerrar sesión', closeMenu: 'Cerrar menú', notifications: 'Ver recordatorios de pago', closeNotifications: 'Cerrar recordatorios', enableNotifications: 'Activar notificaciones', notificationsBlocked: 'Las notificaciones están bloqueadas en el navegador.' }, notifications: { title: 'Recordatorio de pagos', dueToday: 'Vence hoy', noneToday: 'No tienes pagos fijos pendientes para hoy.' }, profile: { title: 'Perfil de Usuario', subtitle: 'Gestiona tu información personal y configuración de cuenta.', verified: 'Verificado', edit: 'Editar perfil', changePassword: 'Cambiar contraseña', personalInformation: 'INFORMACIÓN PERSONAL', email: 'Correo electrónico', phone: 'Teléfono', location: 'Ubicación', language: 'Idioma', exportData: 'EXPORTAR DATOS', exportDescription: 'Descarga una copia de tu actividad financiera y configuración.', json: 'Formato JSON', csv: 'Tabla CSV', lastExport: 'Última exportación: {{date}}.', activityHistory: 'HISTORIAL DE ACTIVIDAD', viewAll: 'Ver todo', action: 'Acción', device: 'Dispositivo', dateTime: 'Fecha y hora', login: 'Inicio de sesión', dataExport: 'Exportación de datos', passwordChange: 'Cambio de contraseña' }, user: { security: 'SEGURIDAD Y ACCESO', personalInformation: 'INFORMACIÓN PERSONAL', fullName: 'Nombre completo', emailAddress: 'Correo electrónico', phoneNumber: 'Número de teléfono', street: 'Calle', houseNumber: 'Número', city: 'Ciudad', country: 'País', interfaceLanguage: 'Idioma de la interfaz', cancel: 'Cancelar', saveChanges: 'Guardar cambios', changePassword: 'CAMBIAR CONTRASEÑA', currentPassword: 'Contraseña actual', newPassword: 'Nueva contraseña', confirmNewPassword: 'Confirmar nueva contraseña', currentPasswordPlaceholder: 'Introduce la contraseña actual', newPasswordPlaceholder: 'Introduce la nueva contraseña', confirmPasswordPlaceholder: 'Confirma la nueva contraseña', allFieldsRequired: 'Todos los campos son obligatorios', passwordsMismatch: 'Las nuevas contraseñas no coinciden', passwordLength: 'La contraseña debe tener al menos 6 caracteres', passwordUpdated: 'Contraseña actualizada correctamente', passwordUpdateFailed: 'No se pudo actualizar la contraseña' } }

const loginPageEs = { headline: 'Domina tu capital con', headlineAccent: 'análisis de precisión', headlineSuffix: '.', description: 'Experimenta la nueva generación de gestión financiera. Controles centralizados, información en tiempo real y seguridad de nivel institucional para tus activos.', monthlyGrowth: 'CRECIMIENTO MENSUAL', activeAccounts: 'CUENTAS ACTIVAS', dashboardAlt: 'Panel de datos financieros', joinProfessionals: 'Únete a más de 10.000 profesionales que gestionan su patrimonio.', termsPrefix: 'Al registrarte, aceptas nuestros', termsOfService: 'Términos de servicio', and: 'y', privacyPolicy: 'Política de privacidad', continueWith: 'O CONTINÚA CON', mobileApp: 'APLICACIÓN MÓVIL PRÓXIMAMENTE', loginError: 'Error al iniciar sesión', registerError: 'Error al registrarse' }
const profileDisplayEs = { activityBrowser: 'Chrome / macOS', activityMadrid: 'Madrid, ES (192.168.1.1)', activityDevice: 'FinTrack App / iPhone 14', activityBarcelona: 'Barcelona, ES (84.12.34.56)', deleteProfile: 'Eliminar perfil', deleteProfileAria: 'Eliminar {{name}}' }
const fr = {
  ...en,
  languageNames: { en: 'Anglais', es: 'Espagnol', fr: 'Français', it: 'Italien', nl: 'Néerlandais' },
  currencyNames: { EUR: 'Euro (€)', USD: 'Dollar américain ($)', GBP: 'Livre sterling (£)', JPY: 'Yen (¥)' },
  settingsExtra: { ...en.settingsExtra, profiles: 'Profils', workspaces: 'Espaces de travail', loadingProfiles: 'Chargement des profils...', active: 'actif', noProfiles: 'Aucun profil n’est encore configuré.', newProfilePlaceholder: 'Nom du nouveau profil', individual: 'Individuel', family: 'Famille', business: 'Entreprise', add: 'Ajouter', generalPreferences: 'Préférences générales', notifications: 'Notifications', notificationPrompt: 'Choisissez ce que vous souhaitez recevoir', yourData: 'Vos données', exportInformation: 'Exporter les informations', preparingExport: 'Préparation de l’exportation...', accountManagement: 'Gestion du compte', deactivation: 'Désactivation', unavailable: 'Indisponible', updatePassword: 'Mettre à jour le mot de passe', updating: 'Mise à jour...', deleteProfile: 'Supprimer le profil' },
  navigation: { profile: 'Profil', signOut: 'Se déconnecter', closeMenu: 'Fermer le menu', notifications: 'Voir les rappels de paiement', closeNotifications: 'Fermer les rappels', enableNotifications: 'Activer les notifications', notificationsBlocked: 'Les notifications sont bloquées dans le navigateur.' },
  notifications: { title: 'Rappel de paiement', dueToday: 'Échéance aujourd’hui', noneToday: 'Aucun paiement fixe en attente aujourd’hui.' },
  loginPage: { headline: 'Maîtrisez votre capital avec', headlineAccent: 'une analyse de précision', headlineSuffix: '.', description: 'Découvrez la nouvelle génération de gestion financière. Contrôles centralisés, informations en temps réel et sécurité de niveau institutionnel pour vos actifs.', monthlyGrowth: 'CROISSANCE MENSUELLE', activeAccounts: 'COMPTES ACTIFS', dashboardAlt: 'Tableau de données financières', joinProfessionals: 'Rejoignez plus de 10 000 professionnels qui gèrent leur patrimoine.', termsPrefix: 'En vous inscrivant, vous acceptez nos', termsOfService: 'Conditions d’utilisation', and: 'et notre', privacyPolicy: 'Politique de confidentialité', continueWith: 'OU CONTINUEZ AVEC', mobileApp: 'APPLICATION MOBILE BIENTÔT DISPONIBLE', loginError: 'Erreur de connexion', registerError: 'Erreur lors de l’inscription' },
  profile: { ...en.profile, title: 'Profil utilisateur', subtitle: 'Gérez vos informations personnelles et les paramètres de votre compte.', verified: 'Vérifié', edit: 'Modifier le profil', changePassword: 'Modifier le mot de passe', personalInformation: 'INFORMATIONS PERSONNELLES', email: 'E-mail', phone: 'Téléphone', location: 'Lieu', language: 'Langue', exportData: 'EXPORTER LES DONNÉES', exportDescription: 'Téléchargez une copie de votre activité financière et de vos paramètres.', json: 'Format JSON', csv: 'Tableau CSV', lastExport: 'Dernière exportation le {{date}}.', activityHistory: 'HISTORIQUE DE L’ACTIVITÉ', viewAll: 'Tout afficher', action: 'Action', device: 'Appareil', dateTime: 'Date et heure', login: 'Connexion', dataExport: 'Exportation des données', passwordChange: 'Modification du mot de passe', deleteProfile: 'Supprimer le profil', deleteProfileAria: 'Supprimer {{name}}' },
  user: { ...en.user, security: 'SÉCURITÉ ET ACCÈS', personalInformation: 'INFORMATIONS PERSONNELLES', fullName: 'Nom complet', emailAddress: 'Adresse e-mail', phoneNumber: 'Numéro de téléphone', street: 'Rue', houseNumber: 'Numéro', city: 'Ville', country: 'Pays', interfaceLanguage: 'Langue de l’interface', cancel: 'Annuler', saveChanges: 'Enregistrer les modifications', changePassword: 'MODIFIER LE MOT DE PASSE', currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe', confirmNewPassword: 'Confirmer le nouveau mot de passe', currentPasswordPlaceholder: 'Saisissez le mot de passe actuel', newPasswordPlaceholder: 'Saisissez le nouveau mot de passe', confirmPasswordPlaceholder: 'Confirmez le nouveau mot de passe', allFieldsRequired: 'Tous les champs sont obligatoires', passwordsMismatch: 'Les nouveaux mots de passe ne correspondent pas', passwordLength: 'Le mot de passe doit comporter au moins 6 caractères', passwordUpdated: 'Mot de passe mis à jour', passwordUpdateFailed: 'Échec de la mise à jour du mot de passe' },
}
const it = { ...fr, languageNames: { en: 'Inglese', es: 'Spagnolo', fr: 'Francese', it: 'Italiano', nl: 'Olandese' }, navigation: { profile: 'Profilo', signOut: 'Esci', closeMenu: 'Chiudi menu', notifications: 'Vedi promemoria pagamenti', closeNotifications: 'Chiudi promemoria', enableNotifications: 'Attiva notifiche', notificationsBlocked: 'Le notifiche sono bloccate nel browser.' }, notifications: { title: 'Promemoria pagamento', dueToday: 'Scade oggi', noneToday: 'Non hai pagamenti fissi in sospeso oggi.' }, loginPage: { ...fr.loginPage, headline: 'Gestisci il tuo capitale con', headlineAccent: 'analisi di precisione', description: 'Scopri la nuova generazione della gestione finanziaria. Controlli centralizzati, dati in tempo reale e sicurezza di livello istituzionale per i tuoi asset.', monthlyGrowth: 'CRESCITA MENSILE', activeAccounts: 'ACCOUNT ATTIVI', termsOfService: 'Termini di servizio', privacyPolicy: 'Informativa sulla privacy', loginError: 'Errore di accesso', registerError: 'Errore di registrazione' }, profile: { ...fr.profile, title: 'Profilo utente', subtitle: 'Gestisci le informazioni personali e le impostazioni del tuo account.', verified: 'Verificato', edit: 'Modifica profilo', changePassword: 'Cambia password', personalInformation: 'INFORMAZIONI PERSONALI', email: 'Email', location: 'Posizione', language: 'Lingua', exportData: 'ESPORTA DATI', viewAll: 'Vedi tutto', dataExport: 'Esportazione dati', passwordChange: 'Cambio password', deleteProfile: 'Elimina profilo', deleteProfileAria: 'Elimina {{name}}' }, user: { ...fr.user, security: 'SICUREZZA E ACCESSO', personalInformation: 'INFORMAZIONI PERSONALI', fullName: 'Nome completo', emailAddress: 'Indirizzo email', phoneNumber: 'Numero di telefono', street: 'Via', houseNumber: 'Numero', city: 'Città', country: 'Paese', interfaceLanguage: 'Lingua dell’interfaccia', saveChanges: 'Salva modifiche', changePassword: 'CAMBIA PASSWORD', currentPassword: 'Password attuale', newPassword: 'Nuova password', confirmNewPassword: 'Conferma nuova password', passwordsMismatch: 'Le nuove password non coincidono', passwordUpdated: 'Password aggiornata correttamente' } }
const nl = { ...fr, languageNames: { en: 'Engels', es: 'Spaans', fr: 'Frans', it: 'Italiaans', nl: 'Nederlands' }, navigation: { profile: 'Profiel', signOut: 'Uitloggen', closeMenu: 'Menu sluiten', notifications: 'Betaalherinneringen bekijken', closeNotifications: 'Herinneringen sluiten', enableNotifications: 'Meldingen inschakelen', notificationsBlocked: 'Meldingen zijn geblokkeerd in de browser.' }, notifications: { title: 'Betaalherinnering', dueToday: 'Vandaag verschuldigd', noneToday: 'Je hebt vandaag geen openstaande vaste betalingen.' }, loginPage: { ...fr.loginPage, headline: 'Beheer je vermogen met', headlineAccent: 'precisieanalyse', description: 'Ervaar de volgende generatie financieel beheer. Gecentraliseerde controle, realtime inzichten en beveiliging op institutioneel niveau voor je vermogen.', monthlyGrowth: 'MAANDELIJKSE GROEI', activeAccounts: 'ACTIEVE ACCOUNTS', termsOfService: 'Servicevoorwaarden', privacyPolicy: 'Privacybeleid', loginError: 'Fout bij inloggen', registerError: 'Fout bij registreren' }, profile: { ...fr.profile, title: 'Gebruikersprofiel', subtitle: 'Beheer je persoonlijke gegevens en accountinstellingen.', verified: 'Geverifieerd', edit: 'Profiel bewerken', changePassword: 'Wachtwoord wijzigen', personalInformation: 'PERSOONLIJKE GEGEVENS', email: 'E-mail', location: 'Locatie', language: 'Taal', exportData: 'GEGEVENS EXPORTEREN', viewAll: 'Alles bekijken', dataExport: 'Gegevensexport', passwordChange: 'Wachtwoord wijzigen', deleteProfile: 'Profiel verwijderen', deleteProfileAria: '{{name}} verwijderen' }, user: { ...fr.user, security: 'BEVEILIGING EN TOEGANG', personalInformation: 'PERSOONLIJKE GEGEVENS', fullName: 'Volledige naam', emailAddress: 'E-mailadres', phoneNumber: 'Telefoonnummer', street: 'Straat', houseNumber: 'Huisnummer', city: 'Stad', country: 'Land', interfaceLanguage: 'Interfacetaal', saveChanges: 'Wijzigingen opslaan', changePassword: 'WACHTWOORD WIJZIGEN', currentPassword: 'Huidig wachtwoord', newPassword: 'Nieuw wachtwoord', confirmNewPassword: 'Nieuw wachtwoord bevestigen', passwordsMismatch: 'De nieuwe wachtwoorden komen niet overeen', passwordUpdated: 'Wachtwoord bijgewerkt' } }
const resources = { en, es: { ...en, ...es, profile: { ...en.profile, ...es.profile, ...profileDisplayEs }, loginPage: loginPageEs }, fr, it, nl }
Object.entries(resources).forEach(([language, value]) => i18n.addResourceBundle(language, 'translation', value, true, true))
export { resources as profileResources }
