import i18n from './config'

export const secondPassResources = {
  en: {
    budget: { define: 'Define your budget', placeholder: 'Define your budget', saving: 'Saving...', submit: 'Set budget' },
    categories: { title: 'Categories', new: '+ New', edit: 'Edit category', name: 'Name', placeholder: 'e.g. Transport', color: 'Color', icon: 'Icon', iconPlaceholder: 'Search icon...', noIconResults: 'No results', selectedIcon: 'Selected', create: 'Create', empty: 'No categories. Create one to organize your expenses.', editAction: 'Edit category', deleteAction: 'Delete category', confirmDelete: 'Are you sure you want to delete this category?', selectColor: 'Select color {{color}}', monthlyLimit: 'Monthly limit', monthlyLimitPlaceholder: 'optional, e.g. 500' },
    expense: { noRecords: 'No expense records', list: 'Expense list', update: 'Update expense', new: 'New expense', name: 'Expense name', namePlaceholder: 'Add expense', amount: 'Expense amount', amountPlaceholder: 'Add amount, e.g. 300', category: 'Category', select: '-- Select --', addCategory: 'Add new category', date: 'Expense date', status: 'Payment status', pending: 'Pending', paid: 'Paid', partial: 'Partial payment', partialAmount: 'Partial amount paid', commentOptional: 'Comment (optional)', commentPlaceholder: 'Add a comment...', saveChanges: 'Save changes', register: 'Record expense', close: 'Close modal', delete: 'Delete expense', confirmDelete: 'Are you sure you want to delete this expense? This cannot be undone.', paidAmount: '{{amount}} paid', markStatus: 'Change payment status', commentsHistory: 'Comment history', title: 'Expenses', description: 'Manage your expenses and track your spending.', addTransaction: 'Add transaction', transactionDetails: 'Transaction details', editTransaction: 'Edit transaction', merchant: 'Merchant / Recipient', amountLabel: 'Amount', datePayment: 'Payment date', statusLabel: 'Status', confirmPayment: 'Confirm payment', details: 'Tap to view details', recent: 'Recent transactions', showing: 'Showing {{count}} items', loadMore: 'Load more transactions', saveStatus: 'Save status', remaining: 'Remaining balance', paymentComments: 'Payment comments', receipt: 'Receipt', required: 'All fields are required', amountPositive: 'The amount must be greater than 0', overBudget: 'This expense exceeds the budget', paidSoFar: 'Amount paid so far', partialCommentPlaceholder: 'Explain the payment schedule or reason for partial payment...', saveTransaction: 'Save transaction', createError: 'Error creating expense', saveError: 'Error saving expense', confirmError: 'Error confirming payment', typeExpense: 'Expense', typeSaving: 'Saving' },
    filters: { dateRange: 'Date range', allDates: 'All dates', last7: 'Last 7 days', last30: 'Last 30 days', currentMonth: 'Current month', previousQuarter: 'Previous quarter', category: 'Category', allCategories: 'All categories', paymentStatus: 'Payment status', all: 'All', filterExpenses: 'Filter expenses' },
    budgetTracker: { spentPercentage: '{{percentage}}% spent', resetting: 'Resetting...', reset: 'Reset app' },
    icons: { restaurant: 'Restaurant', lunch_dining: 'Food', local_cafe: 'Cafe', coffee: 'Coffee shop', shopping_cart: 'Shopping', store: 'Store', local_grocery_store: 'Grocery store', home: 'Home', house: 'House', apartment: 'Apartment', electric_bolt: 'Electricity', water_drop: 'Water', wifi: 'Internet', phone_android: 'Phone', devices: 'Devices', directions_car: 'Car', local_gas_station: 'Gasoline', build: 'Maintenance', local_hospital: 'Hospital', local_pharmacy: 'Pharmacy', favorite: 'Health', spa: 'Wellness', fitness_center: 'Gym', sports_esports: 'Sports', school: 'Education', menu_book: 'Books', child_care: 'Children', family_restroom: 'Family', pets: 'Pets', checkroom: 'Clothing', content_cut: 'Hairdresser', flight: 'Travel', hotel: 'Hotel', movie: 'Cinema', music_note: 'Music', videocam: 'Streaming', sports_bar: 'Leisure', local_bar: 'Bar', cake: 'Celebrations', card_giftcard: 'Gifts', savings: 'Savings', account_balance: 'Bank', payments: 'Payments', receipt_long: 'Bills', credit_card: 'Card', paid: 'Money', trending_up: 'Investments', security: 'Insurance', volunteer_activism: 'Donations', redeem: 'Points', local_shipping: 'Shipping', delivery_dining: 'Delivery', dry_cleaning: 'Laundry', emoji_people: 'Social', groups: 'Groups', mail: 'Mail', print: 'Printing', camera: 'Photography', brush: 'Art', construction: 'Construction', agriculture: 'Garden', flag: 'Flags', star: 'Favorites', lock: 'Security', notifications: 'Notifications', cloud: 'Cloud', palette: 'Palette', toys: 'Toys', psychology: 'Psychology', auto_stories: 'Studies', work: 'Work', business_center: 'Business' },
    comments: { comment: 'Comment', loading: 'Loading comments...', emptyTitle: 'No comments yet', emptyText: 'Payment notes and clarifications will appear here.', delete: 'Delete', confirmDelete: 'Are you sure you want to delete this comment?', placeholder: 'Add a comment...', publish: 'Post', now: 'Now', minutes: '{{count}} min', hours: '{{count}} h', days: '{{count}} d', anonymous: 'anonymous', user: 'user_{{id}}' },
    upload: { fileTooLarge: 'File size must be under 5MB', scanning: 'Scanning receipt...', extracting: 'Extracting merchant, amount and date', preview: 'Receipt preview', upload: 'Upload receipt or invoice', formats: 'PDF, PNG or JPG up to 5MB', remove: 'Remove receipt', download: 'Download receipt', scanError: 'Error scanning receipt', receiptFile: 'receipt_invoice.pdf', fileSize: '1.2 MB' },
  },
  es: {
    budget: { define: 'Define tu presupuesto', placeholder: 'Define tu presupuesto', saving: 'Guardando...', submit: 'Definir presupuesto' },
    categories: { title: 'Categorías', new: '+ Nueva', edit: 'Editar categoría', name: 'Nombre', placeholder: 'Ej. Transporte', color: 'Color', icon: 'Icono', iconPlaceholder: 'Buscar icono...', noIconResults: 'Sin resultados', selectedIcon: 'Seleccionado', create: 'Crear', empty: 'Sin categorías. Crea una para organizar tus gastos.', editAction: 'Editar categoría', deleteAction: 'Eliminar categoría', confirmDelete: '¿Seguro que deseas eliminar esta categoría?', selectColor: 'Seleccionar color {{color}}', monthlyLimit: 'Límite mensual', monthlyLimitPlaceholder: 'opcional, ej. 500' },
    expense: { noRecords: 'No hay registros de gastos', list: 'Listado de gastos', update: 'Actualizar gasto', new: 'Nuevo gasto', name: 'Nombre del gasto', namePlaceholder: 'Añadir gasto', amount: 'Cantidad del gasto', amountPlaceholder: 'Añadir cantidad, ej. 300', category: 'Categoría', select: '-- Seleccione --', addCategory: 'Añadir nueva categoría', date: 'Fecha del gasto', status: 'Estado de pago', pending: 'Pendiente', paid: 'Pagado', partial: 'Pago parcial', partialAmount: 'Monto parcial pagado', commentOptional: 'Comentario (opcional)', commentPlaceholder: 'Agregar comentario...', saveChanges: 'Guardar cambios', register: 'Registrar gasto', close: 'Cerrar modal', delete: 'Eliminar gasto', confirmDelete: '¿Estás seguro de que quieres eliminar este gasto? No se puede recuperar.', paidAmount: '{{amount}} pagados', markStatus: 'Cambiar estado de pago', commentsHistory: 'Historial de comentarios', title: 'Gastos', description: 'Gestiona tus gastos y controla tus pagos.', addTransaction: 'Añadir transacción', transactionDetails: 'Detalles de la transacción', editTransaction: 'Editar transacción', merchant: 'Comercio / Beneficiario', amountLabel: 'Importe', datePayment: 'Fecha de pago', statusLabel: 'Estado', confirmPayment: 'Confirmar pago', details: 'Toca para ver detalles', recent: 'Transacciones recientes', showing: 'Mostrando {{count}} elementos', loadMore: 'Cargar más transacciones', saveStatus: 'Guardar estado', remaining: 'Saldo restante', paymentComments: 'Comentarios del pago', receipt: 'Recibo' },
    filters: { dateRange: 'Rango de fechas', allDates: 'Todas las fechas', last7: 'Últimos 7 días', last30: 'Últimos 30 días', currentMonth: 'Mes actual', previousQuarter: 'Trimestre anterior', category: 'Categoría', allCategories: 'Todas las categorías', paymentStatus: 'Estado de pago', all: 'Todos', filterExpenses: 'Filtrar gastos' },
    budgetTracker: { spentPercentage: '{{percentage}}% gastado', resetting: 'Reiniciando...', reset: 'Restablecer aplicación' },
    icons: { restaurant: 'Restaurante', lunch_dining: 'Comida', local_cafe: 'Café', coffee: 'Cafetería', shopping_cart: 'Compras', store: 'Tienda', local_grocery_store: 'Supermercado', home: 'Hogar', house: 'Casa', apartment: 'Apartamento', electric_bolt: 'Electricidad', water_drop: 'Agua', wifi: 'Internet', phone_android: 'Teléfono', devices: 'Dispositivos', directions_car: 'Auto', local_gas_station: 'Gasolina', build: 'Mantenimiento', local_hospital: 'Hospital', local_pharmacy: 'Farmacia', favorite: 'Salud', spa: 'Bienestar', fitness_center: 'Gimnasio', sports_esports: 'Deportes', school: 'Educación', menu_book: 'Libros', child_care: 'Hijos', family_restroom: 'Familia', pets: 'Mascotas', checkroom: 'Ropa', content_cut: 'Peluquería', flight: 'Viajes', hotel: 'Hotel', movie: 'Cine', music_note: 'Música', videocam: 'Streaming', sports_bar: 'Ocio', local_bar: 'Bar', cake: 'Celebraciones', card_giftcard: 'Regalos', savings: 'Ahorro', account_balance: 'Banco', payments: 'Pagos', receipt_long: 'Recibos', credit_card: 'Tarjeta', paid: 'Dinero', trending_up: 'Inversiones', security: 'Seguros', volunteer_activism: 'Donaciones', redeem: 'Puntos', local_shipping: 'Envíos', delivery_dining: 'Delivery', dry_cleaning: 'Lavandería', emoji_people: 'Social', groups: 'Grupos', mail: 'Correo', print: 'Impresión', camera: 'Fotografía', brush: 'Arte', construction: 'Construcción', agriculture: 'Jardín', flag: 'Banderas', star: 'Favoritos', lock: 'Seguridad', notifications: 'Notificaciones', cloud: 'Nube', palette: 'Paleta', toys: 'Juguetes', psychology: 'Psicología', auto_stories: 'Estudios', work: 'Trabajo', business_center: 'Negocios' },
    comments: { loading: 'Cargando comentarios...', emptyTitle: 'Aún no hay comentarios', emptyText: 'Las aclaraciones o notas de este pago aparecerán aquí.', delete: 'Eliminar', confirmDelete: '¿Seguro que quieres eliminar este comentario?', placeholder: 'Agrega un comentario...', publish: 'Publicar', now: 'Ahora', minutes: '{{count}} min', hours: '{{count}} h', days: '{{count}} d', anonymous: 'anónimo', user: 'usuario_{{id}}' },
    upload: { fileTooLarge: 'El archivo debe ocupar menos de 5 MB', scanning: 'Analizando recibo...', extracting: 'Extrayendo comercio, importe y fecha', preview: 'Vista previa del recibo', upload: 'Subir recibo o factura', formats: 'PDF, PNG o JPG de hasta 5 MB', remove: 'Eliminar recibo', download: 'Descargar recibo' },
  },
  fr: {
    budget: { define: 'Définissez votre budget', placeholder: 'Définissez votre budget', saving: 'Enregistrement...', submit: 'Définir le budget' },
    categories: { title: 'Catégories', new: '+ Nouvelle', edit: 'Modifier la catégorie', name: 'Nom', placeholder: 'ex. Transport', color: 'Couleur', icon: 'Icône', iconPlaceholder: 'Rechercher une icône...', noIconResults: 'Aucun résultat', selectedIcon: 'Sélectionnée', create: 'Créer', empty: 'Aucune catégorie. Créez-en une pour organiser vos dépenses.', editAction: 'Modifier la catégorie', deleteAction: 'Supprimer la catégorie', confirmDelete: 'Voulez-vous vraiment supprimer cette catégorie ?', selectColor: 'Sélectionner la couleur {{color}}' },
    expense: { noRecords: 'Aucun enregistrement de dépense', list: 'Liste des dépenses', update: 'Mettre à jour la dépense', new: 'Nouvelle dépense', name: 'Nom de la dépense', namePlaceholder: 'Ajouter une dépense', amount: 'Montant de la dépense', amountPlaceholder: 'Ajouter un montant, ex. 300', category: 'Catégorie', select: '-- Sélectionner --', addCategory: 'Ajouter une catégorie', date: 'Date de la dépense', status: 'Statut du paiement', pending: 'En attente', paid: 'Payée', partial: 'Paiement partiel', partialAmount: 'Montant partiellement payé', commentOptional: 'Commentaire (facultatif)', commentPlaceholder: 'Ajouter un commentaire...', saveChanges: 'Enregistrer les modifications', register: 'Enregistrer la dépense', close: 'Fermer la fenêtre', delete: 'Supprimer la dépense', confirmDelete: 'Voulez-vous vraiment supprimer cette dépense ? Cette action est irréversible.', paidAmount: '{{amount}} payé(s)', markStatus: 'Modifier le statut du paiement', commentsHistory: 'Historique des commentaires', title: 'Dépenses', description: 'Gérez vos dépenses et suivez vos paiements.', addTransaction: 'Ajouter une transaction', transactionDetails: 'Détails de la transaction', editTransaction: 'Modifier la transaction', merchant: 'Commerçant / bénéficiaire', amountLabel: 'Montant', datePayment: 'Date du paiement', statusLabel: 'Statut', confirmPayment: 'Confirmer le paiement', details: 'Touchez pour voir les détails', recent: 'Transactions récentes', showing: 'Affichage de {{count}} éléments', loadMore: 'Charger plus de transactions', saveStatus: 'Enregistrer le statut', remaining: 'Solde restant', paymentComments: 'Commentaires du paiement', receipt: 'Reçu', required: 'Tous les champs sont obligatoires', amountPositive: 'Le montant doit être supérieur à 0', overBudget: 'Cette dépense dépasse le budget', paidSoFar: 'Montant déjà payé', partialCommentPlaceholder: 'Expliquez l’échéancier ou la raison du paiement partiel...', saveTransaction: 'Enregistrer la transaction', createError: 'Erreur lors de la création de la dépense', saveError: 'Erreur lors de l’enregistrement de la dépense', confirmError: 'Erreur lors de la confirmation du paiement' },
    filters: { dateRange: 'Période', allDates: 'Toutes les dates', last7: '7 derniers jours', last30: '30 derniers jours', currentMonth: 'Mois en cours', previousQuarter: 'Trimestre précédent', category: 'Catégorie', allCategories: 'Toutes les catégories', paymentStatus: 'Statut du paiement', all: 'Toutes', filterExpenses: 'Filtrer les dépenses' },
    budgetTracker: { spentPercentage: '{{percentage}} % dépensé', resetting: 'Réinitialisation...', reset: 'Réinitialiser l’application' },
    icons: { restaurant: 'Restaurant', lunch_dining: 'Alimentation', local_cafe: 'Café', coffee: 'Café', shopping_cart: 'Achats', store: 'Magasin', local_grocery_store: 'Épicerie', home: 'Maison', house: 'Domicile', apartment: 'Appartement', electric_bolt: 'Électricité', water_drop: 'Eau', wifi: 'Internet', phone_android: 'Téléphone', devices: 'Appareils', directions_car: 'Voiture', local_gas_station: 'Carburant', build: 'Entretien', local_hospital: 'Hôpital', local_pharmacy: 'Pharmacie', favorite: 'Santé', spa: 'Bien-être', fitness_center: 'Salle de sport', sports_esports: 'Sports', school: 'Éducation', menu_book: 'Livres', child_care: 'Enfants', family_restroom: 'Famille', pets: 'Animaux', checkroom: 'Vêtements', content_cut: 'Coiffeur', flight: 'Voyage', hotel: 'Hôtel', movie: 'Cinéma', music_note: 'Musique', videocam: 'Streaming', sports_bar: 'Loisirs', local_bar: 'Bar', cake: 'Célébrations', card_giftcard: 'Cadeaux', savings: 'Épargne', account_balance: 'Banque', payments: 'Paiements', receipt_long: 'Factures', credit_card: 'Carte', paid: 'Argent', trending_up: 'Investissements', security: 'Assurance', volunteer_activism: 'Dons', redeem: 'Points', local_shipping: 'Expédition', delivery_dining: 'Livraison', dry_cleaning: 'Blanchisserie', emoji_people: 'Social', groups: 'Groupes', mail: 'Courrier', print: 'Impression', camera: 'Photographie', brush: 'Art', construction: 'Construction', agriculture: 'Jardin', flag: 'Drapeaux', star: 'Favoris', lock: 'Sécurité', notifications: 'Notifications', cloud: 'Cloud', palette: 'Palette', toys: 'Jouets', psychology: 'Psychologie', auto_stories: 'Études', work: 'Travail', business_center: 'Entreprise' },
    comments: { comment: 'Commentaire', loading: 'Chargement des commentaires...', emptyTitle: 'Aucun commentaire', emptyText: 'Les notes et précisions du paiement apparaîtront ici.', delete: 'Supprimer', confirmDelete: 'Voulez-vous vraiment supprimer ce commentaire ?', placeholder: 'Ajouter un commentaire...', publish: 'Publier', now: 'Maintenant', minutes: '{{count}} min', hours: '{{count}} h', days: '{{count}} j', anonymous: 'anonyme', user: 'utilisateur_{{id}}' },
    upload: { fileTooLarge: 'Le fichier doit faire moins de 5 Mo', scanning: 'Analyse du reçu...', extracting: 'Extraction du commerçant, du montant et de la date', preview: 'Aperçu du reçu', upload: 'Importer un reçu ou une facture', formats: 'PDF, PNG ou JPG jusqu’à 5 Mo', remove: 'Supprimer le reçu', download: 'Télécharger le reçu', scanError: 'Erreur lors de l’analyse du reçu', receiptFile: 'recu_facture.pdf', fileSize: '1,2 Mo' },
  },
  it: {
    budget: { define: 'Definisci il tuo budget', placeholder: 'Definisci il tuo budget', saving: 'Salvataggio...', submit: 'Imposta budget' },
    categories: { title: 'Categorie', new: '+ Nuova', edit: 'Modifica categoria', name: 'Nome', placeholder: 'es. Trasporti', color: 'Colore', icon: 'Icona', iconPlaceholder: 'Cerca icona...', noIconResults: 'Nessun risultato', selectedIcon: 'Selezionata', create: 'Crea', empty: 'Nessuna categoria. Creane una per organizzare le spese.', editAction: 'Modifica categoria', deleteAction: 'Elimina categoria', confirmDelete: 'Vuoi davvero eliminare questa categoria?', selectColor: 'Seleziona colore {{color}}' },
    expense: { noRecords: 'Nessun movimento di spesa', list: 'Elenco spese', update: 'Aggiorna spesa', new: 'Nuova spesa', name: 'Nome della spesa', namePlaceholder: 'Aggiungi spesa', amount: 'Importo della spesa', amountPlaceholder: 'Aggiungi importo, es. 300', category: 'Categoria', select: '-- Seleziona --', addCategory: 'Aggiungi categoria', date: 'Data della spesa', status: 'Stato del pagamento', pending: 'In sospeso', paid: 'Pagata', partial: 'Pagamento parziale', partialAmount: 'Importo pagato parzialmente', commentOptional: 'Commento (facoltativo)', commentPlaceholder: 'Aggiungi un commento...', saveChanges: 'Salva modifiche', register: 'Registra spesa', close: 'Chiudi finestra', delete: 'Elimina spesa', confirmDelete: 'Vuoi davvero eliminare questa spesa? Non può essere annullato.', paidAmount: '{{amount}} pagato/i', markStatus: 'Cambia stato del pagamento', commentsHistory: 'Cronologia commenti', title: 'Spese', description: 'Gestisci le spese e controlla i pagamenti.', addTransaction: 'Aggiungi transazione', transactionDetails: 'Dettagli transazione', editTransaction: 'Modifica transazione', merchant: 'Commerciante / beneficiario', amountLabel: 'Importo', datePayment: 'Data del pagamento', statusLabel: 'Stato', confirmPayment: 'Conferma pagamento', details: 'Tocca per vedere i dettagli', recent: 'Transazioni recenti', showing: 'Visualizzazione di {{count}} elementi', loadMore: 'Carica altre transazioni', saveStatus: 'Salva stato', remaining: 'Saldo residuo', paymentComments: 'Commenti sul pagamento', receipt: 'Ricevuta', required: 'Tutti i campi sono obbligatori', amountPositive: 'L’importo deve essere maggiore di 0', overBudget: 'Questa spesa supera il budget', paidSoFar: 'Importo pagato finora', partialCommentPlaceholder: 'Spiega il piano di pagamento o il motivo del pagamento parziale...', saveTransaction: 'Salva transazione', createError: 'Errore nella creazione della spesa', saveError: 'Errore nel salvataggio della spesa', confirmError: 'Errore nella conferma del pagamento' },
    filters: { dateRange: 'Intervallo di date', allDates: 'Tutte le date', last7: 'Ultimi 7 giorni', last30: 'Ultimi 30 giorni', currentMonth: 'Mese corrente', previousQuarter: 'Trimestre precedente', category: 'Categoria', allCategories: 'Tutte le categorie', paymentStatus: 'Stato del pagamento', all: 'Tutte', filterExpenses: 'Filtra spese' },
    budgetTracker: { spentPercentage: '{{percentage}}% speso', resetting: 'Ripristino...', reset: 'Reimposta app' },
    icons: { restaurant: 'Ristorante', lunch_dining: 'Cibo', local_cafe: 'Bar', coffee: 'Caffetteria', shopping_cart: 'Acquisti', store: 'Negozio', local_grocery_store: 'Alimentari', home: 'Casa', house: 'Abitazione', apartment: 'Appartamento', electric_bolt: 'Elettricità', water_drop: 'Acqua', wifi: 'Internet', phone_android: 'Telefono', devices: 'Dispositivi', directions_car: 'Auto', local_gas_station: 'Carburante', build: 'Manutenzione', local_hospital: 'Ospedale', local_pharmacy: 'Farmacia', favorite: 'Salute', spa: 'Benessere', fitness_center: 'Palestra', sports_esports: 'Sport', school: 'Istruzione', menu_book: 'Libri', child_care: 'Bambini', family_restroom: 'Famiglia', pets: 'Animali', checkroom: 'Abbigliamento', content_cut: 'Parrucchiere', flight: 'Viaggi', hotel: 'Hotel', movie: 'Cinema', music_note: 'Musica', videocam: 'Streaming', sports_bar: 'Tempo libero', local_bar: 'Bar', cake: 'Festeggiamenti', card_giftcard: 'Regali', savings: 'Risparmi', account_balance: 'Banca', payments: 'Pagamenti', receipt_long: 'Bollette', credit_card: 'Carta', paid: 'Denaro', trending_up: 'Investimenti', security: 'Assicurazione', volunteer_activism: 'Donazioni', redeem: 'Punti', local_shipping: 'Spedizioni', delivery_dining: 'Consegna', dry_cleaning: 'Lavanderia', emoji_people: 'Sociale', groups: 'Gruppi', mail: 'Posta', print: 'Stampa', camera: 'Fotografia', brush: 'Arte', construction: 'Edilizia', agriculture: 'Giardino', flag: 'Bandiere', star: 'Preferiti', lock: 'Sicurezza', notifications: 'Notifiche', cloud: 'Cloud', palette: 'Tavolozza', toys: 'Giochi', psychology: 'Psicologia', auto_stories: 'Studi', work: 'Lavoro', business_center: 'Azienda' },
    comments: { comment: 'Commento', loading: 'Caricamento commenti...', emptyTitle: 'Nessun commento', emptyText: 'Qui appariranno le note e i chiarimenti sul pagamento.', delete: 'Elimina', confirmDelete: 'Vuoi davvero eliminare questo commento?', placeholder: 'Aggiungi un commento...', publish: 'Pubblica', now: 'Ora', minutes: '{{count}} min', hours: '{{count}} h', days: '{{count}} g', anonymous: 'anonimo', user: 'utente_{{id}}' },
    upload: { fileTooLarge: 'Il file deve essere inferiore a 5 MB', scanning: 'Scansione ricevuta...', extracting: 'Estrazione di commerciante, importo e data', preview: 'Anteprima ricevuta', upload: 'Carica ricevuta o fattura', formats: 'PDF, PNG o JPG fino a 5 MB', remove: 'Rimuovi ricevuta', download: 'Scarica ricevuta', scanError: 'Errore nella scansione della ricevuta', receiptFile: 'ricevuta_fattura.pdf', fileSize: '1,2 MB' },
  },
  nl: {
    budget: { define: 'Stel je budget in', placeholder: 'Stel je budget in', saving: 'Opslaan...', submit: 'Budget instellen' },
    categories: { title: 'Categorieën', new: '+ Nieuwe', edit: 'Categorie bewerken', name: 'Naam', placeholder: 'bijv. Vervoer', color: 'Kleur', icon: 'Pictogram', iconPlaceholder: 'Pictogram zoeken...', noIconResults: 'Geen resultaten', selectedIcon: 'Geselecteerd', create: 'Aanmaken', empty: 'Geen categorieën. Maak er een aan om je uitgaven te ordenen.', editAction: 'Categorie bewerken', deleteAction: 'Categorie verwijderen', confirmDelete: 'Weet je zeker dat je deze categorie wilt verwijderen?', selectColor: 'Kleur selecteren {{color}}' },
    expense: { noRecords: 'Geen uitgaven geregistreerd', list: 'Uitgavenlijst', update: 'Uitgave bijwerken', new: 'Nieuwe uitgave', name: 'Naam van de uitgave', namePlaceholder: 'Uitgave toevoegen', amount: 'Bedrag van de uitgave', amountPlaceholder: 'Bedrag toevoegen, bijv. 300', category: 'Categorie', select: '-- Selecteren --', addCategory: 'Nieuwe categorie toevoegen', date: 'Datum van de uitgave', status: 'Betaalstatus', pending: 'In behandeling', paid: 'Betaald', partial: 'Gedeeltelijke betaling', partialAmount: 'Gedeeltelijk betaald bedrag', commentOptional: 'Opmerking (optioneel)', commentPlaceholder: 'Opmerking toevoegen...', saveChanges: 'Wijzigingen opslaan', register: 'Uitgave registreren', close: 'Venster sluiten', delete: 'Uitgave verwijderen', confirmDelete: 'Weet je zeker dat je deze uitgave wilt verwijderen? Dit kan niet ongedaan worden gemaakt.', paidAmount: '{{amount}} betaald', markStatus: 'Betaalstatus wijzigen', commentsHistory: 'Opmerkingengeschiedenis', title: 'Uitgaven', description: 'Beheer je uitgaven en houd je betalingen bij.', addTransaction: 'Transactie toevoegen', transactionDetails: 'Transactiedetails', editTransaction: 'Transactie bewerken', merchant: 'Handelaar / ontvanger', amountLabel: 'Bedrag', datePayment: 'Betaaldatum', statusLabel: 'Status', confirmPayment: 'Betaling bevestigen', details: 'Tik voor details', recent: 'Recente transacties', showing: '{{count}} items weergegeven', loadMore: 'Meer transacties laden', saveStatus: 'Status opslaan', remaining: 'Resterend saldo', paymentComments: 'Betaalopmerkingen', receipt: 'Bon', required: 'Alle velden zijn verplicht', amountPositive: 'Het bedrag moet groter zijn dan 0', overBudget: 'Deze uitgave overschrijdt het budget', paidSoFar: 'Tot nu toe betaald', partialCommentPlaceholder: 'Leg het betalingsschema of de reden voor de gedeeltelijke betaling uit...', saveTransaction: 'Transactie opslaan', createError: 'Fout bij het aanmaken van de uitgave', saveError: 'Fout bij het opslaan van de uitgave', confirmError: 'Fout bij het bevestigen van de betaling' },
    filters: { dateRange: 'Datumbereik', allDates: 'Alle datums', last7: 'Afgelopen 7 dagen', last30: 'Afgelopen 30 dagen', currentMonth: 'Huidige maand', previousQuarter: 'Vorig kwartaal', category: 'Categorie', allCategories: 'Alle categorieën', paymentStatus: 'Betaalstatus', all: 'Alle', filterExpenses: 'Uitgaven filteren' },
    budgetTracker: { spentPercentage: '{{percentage}}% besteed', resetting: 'Resetten...', reset: 'App resetten' },
    icons: { restaurant: 'Restaurant', lunch_dining: 'Eten', local_cafe: 'Café', coffee: 'Koffiebar', shopping_cart: 'Boodschappen', store: 'Winkel', local_grocery_store: 'Supermarkt', home: 'Woning', house: 'Huis', apartment: 'Appartement', electric_bolt: 'Elektriciteit', water_drop: 'Water', wifi: 'Internet', phone_android: 'Telefoon', devices: 'Apparaten', directions_car: 'Auto', local_gas_station: 'Brandstof', build: 'Onderhoud', local_hospital: 'Ziekenhuis', local_pharmacy: 'Apotheek', favorite: 'Gezondheid', spa: 'Welzijn', fitness_center: 'Sportschool', sports_esports: 'Sport', school: 'Onderwijs', menu_book: 'Boeken', child_care: 'Kinderen', family_restroom: 'Familie', pets: 'Huisdieren', checkroom: 'Kleding', content_cut: 'Kapper', flight: 'Reizen', hotel: 'Hotel', movie: 'Bioscoop', music_note: 'Muziek', videocam: 'Streaming', sports_bar: 'Vrije tijd', local_bar: 'Bar', cake: 'Feestdagen', card_giftcard: 'Cadeaus', savings: 'Sparen', account_balance: 'Bank', payments: 'Betalingen', receipt_long: 'Rekeningen', credit_card: 'Kaart', paid: 'Geld', trending_up: 'Beleggingen', security: 'Verzekering', volunteer_activism: 'Donaties', redeem: 'Punten', local_shipping: 'Verzending', delivery_dining: 'Bezorging', dry_cleaning: 'Stomerij', emoji_people: 'Sociaal', groups: 'Groepen', mail: 'Post', print: 'Afdrukken', camera: 'Fotografie', brush: 'Kunst', construction: 'Bouw', agriculture: 'Tuin', flag: 'Vlaggen', star: 'Favorieten', lock: 'Beveiliging', notifications: 'Meldingen', cloud: 'Cloud', palette: 'Palet', toys: 'Speelgoed', psychology: 'Psychologie', auto_stories: 'Studies', work: 'Werk', business_center: 'Bedrijf' },
    comments: { comment: 'Opmerking', loading: 'Opmerkingen laden...', emptyTitle: 'Nog geen opmerkingen', emptyText: 'Betalingsnotities en toelichtingen verschijnen hier.', delete: 'Verwijderen', confirmDelete: 'Weet je zeker dat je deze opmerking wilt verwijderen?', placeholder: 'Opmerking toevoegen...', publish: 'Plaatsen', now: 'Nu', minutes: '{{count}} min', hours: '{{count}} u', days: '{{count}} d', anonymous: 'anoniem', user: 'gebruiker_{{id}}' },
    upload: { fileTooLarge: 'Het bestand moet kleiner zijn dan 5 MB', scanning: 'Bon scannen...', extracting: 'Handelaar, bedrag en datum ophalen', preview: 'Voorbeeld van de bon', upload: 'Bon of factuur uploaden', formats: 'PDF, PNG of JPG tot 5 MB', remove: 'Bon verwijderen', download: 'Bon downloaden', scanError: 'Fout bij het scannen van de bon', receiptFile: 'bon_factuur.pdf', fileSize: '1,2 MB' },
  },
} as const

Object.entries(secondPassResources).forEach(([language, value]) => {
  i18n.addResourceBundle(language, 'translation', value, true, true)
})
