import i18n from './config'

const resources = {
  en: { support: { categories: { account: 'Account' }, emailPlaceholder: 'you@email.com', articles: { languageTitle: 'Change your interface language', languageSummary: 'Choose the language that best suits you from Settings or your Profile.', language1: 'Open Settings, select Language and format, and choose English, Spanish, French, Italian, or Dutch.', language2: 'Alternatively, open Profile, choose Edit Profile, change Interface Language, and save your changes.', languageTip: 'The selected language is saved to your account and will be restored when you sign in again.' } } },
  es: { support: { categories: { account: 'Cuenta' }, emailPlaceholder: 'tu@correo.com', articles: { languageTitle: 'Cambiar el idioma de la interfaz', languageSummary: 'Elige el idioma que prefieras desde Configuración o desde tu Perfil.', language1: 'Abre Configuración, selecciona Idioma y formato y elige español, inglés, francés, italiano o neerlandés.', language2: 'También puedes abrir Perfil, seleccionar Editar perfil, cambiar el Idioma de la interfaz y guardar los cambios.', languageTip: 'El idioma seleccionado se guarda en tu cuenta y se recupera al volver a iniciar sesión.' } } },
  fr: { support: { categories: { account: 'Compte' }, emailPlaceholder: 'vous@e-mail.com', articles: { languageTitle: "Changer la langue de l'interface", languageSummary: 'Choisissez votre langue depuis Paramètres ou votre Profil.', language1: "Ouvrez Paramètres, sélectionnez Langue et format, puis choisissez l'anglais, l'espagnol, le français, l'italien ou le néerlandais.", language2: "Vous pouvez aussi ouvrir Profil, choisir Modifier le profil, changer la langue de l'interface et enregistrer.", languageTip: 'La langue choisie est enregistrée dans votre compte et restaurée à la prochaine connexion.' } } },
  it: { support: { categories: { account: 'Account' }, emailPlaceholder: 'tu@email.com', articles: { languageTitle: "Cambiare la lingua dell'interfaccia", languageSummary: 'Scegli la lingua preferita da Impostazioni o dal tuo Profilo.', language1: "Apri Impostazioni, seleziona Lingua e formato e scegli inglese, spagnolo, francese, italiano o olandese.", language2: 'In alternativa, apri Profilo, scegli Modifica profilo, cambia la lingua dell’interfaccia e salva le modifiche.', languageTip: 'La lingua scelta viene salvata nel tuo account e ripristinata al prossimo accesso.' } } },
  nl: { support: { categories: { account: 'Account' }, emailPlaceholder: 'jij@email.com', articles: { languageTitle: 'De interfacetaal wijzigen', languageSummary: 'Kies je voorkeurstaal via Instellingen of je Profiel.', language1: 'Open Instellingen, selecteer Taal en indeling en kies Engels, Spaans, Frans, Italiaans of Nederlands.', language2: 'Je kunt ook Profiel openen, Profiel bewerken kiezen, de interfacetaal wijzigen en opslaan.', languageTip: 'De gekozen taal wordt in je account opgeslagen en bij de volgende aanmelding hersteld.' } } },
} as const

Object.entries(resources).forEach(([language, value]) => {
  i18n.addResourceBundle(language, 'translation', value, true, true)
})
